name: Archivar
on:
  schedule:
    - cron: '0 1,7,13,19 * * *'
  workflow_dispatch:

concurrency:
  group: repo-maintenance
  cancel-in-progress: false

permissions:
  contents: write

jobs:
  archive:
    name: archive, commit and push
    runs-on: ubuntu-latest
    timeout-minutes: 330
    env:
      IA_ACCESS_KEY: ${{ secrets.IA_ACCESS_KEY }}
      IA_SECRET_KEY: ${{ secrets.IA_SECRET_KEY }}
      ARCHIVE_COLLECTION: ${{ secrets.ARCHIVE_COLLECTION }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: setup python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'
          cache-dependency-path: requirements.txt
      - name: Python
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Archivar
        run: |
          ./archivar/actualizar.py --max-datasets 999999 --max-minutes 300 --max-errores-archivar 3 --map-mode composed
      - name: Commit
        run: |
          git config --global user.email "geodatos-bot@example.com"
          git config --global user.name "geodatos-bot"
          git add -A
          git diff --quiet && git diff --staged --quiet || (git commit -m "[archive] $(date '+%Y-%m-%d %H:%M')"; git push -q "https://$GITHUB_TOKEN@github.com/mauforonda/geodatos.git" master)
