name: Update
on:
  schedule:
    - cron: '0 4 * * 6'
  workflow_dispatch:
jobs:
  update:
    name: check, update and commit
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@master
      - name: setup python
        uses: actions/setup-python@v1
        with:
          python-version: '3.6'
      - name: setup python and locale
        run: |
          python -m pip install --upgrade pip
          pip install -r update/requirements.txt
      - name: update data
        run: |
         jupyter nbconvert --to notebook --inplace --execute geodatos.ipynb
         ./update/publish.sh geodatos.ipynb 
      - name: commit
        run: |
          git config --global user.email "geodatos-bot@example.com"
          git config --global user.name ""geodatos-bot"
          git add -A
          git diff --quiet && git diff --staged --quiet || (git commit -m "[ci] $(cat update_time)"; git push -q "https://$GH_TOKEN@github.com/mauforonda/geodatos.git" master)
